# This rule is not used by the project headscale-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to headscale.infrado.cloud resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: headscale-operator
    app.kubernetes.io/managed-by: kustomize
  name: headscalepreauthkey-viewer-role
rules:
- apiGroups:
  - headscale.infrado.cloud
  resources:
  - headscalepreauthkeys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - headscale.infrado.cloud
  resources:
  - headscalepreauthkeys/status
  verbs:
  - get
