## Append samples of your project ##
resources:
- headscale_v1beta1_headscale.yaml
- headscale_v1beta1_headscaleuser.yaml
- headscale_v1beta1_headscalepreauthkey.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
